# Generated by Django 5.2.5 on 2025-08-29 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_monday', models.BooleanField()),
                ('due_tuesday', models.BooleanField()),
                ('due_wednesday', models.BooleanField()),
                ('due_thursday', models.BooleanField()),
                ('due_friday', models.BooleanField()),
                ('due_saturday', models.BooleanField()),
                ('due_sunday', models.BooleanField()),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='chores.chore')),
            ],
        ),
    ]
