# Generated by Django 5.2.5 on 2025-08-29 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_choreschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreScheduleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='chores.choreschedule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chore_schedule_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('schedule', 'order'), name='unique_schedule_order'), models.UniqueConstraint(fields=('schedule', 'user'), name='unique_schedule_user')],
            },
        ),
    ]
