# Generated by Django 5.2.5 on 2025-09-05 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0005_choreassignment_completed_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choreschedule',
            name='due_friday',
        ),
        migrations.RemoveField(
            model_name='choreschedule',
            name='due_monday',
        ),
        migrations.RemoveField(
            model_name='choreschedule',
            name='due_saturday',
        ),
        migrations.RemoveField(
            model_name='choreschedule',
            name='due_sunday',
        ),
        migrations.RemoveField(
            model_name='choreschedule',
            name='due_thursday',
        ),
        migrations.RemoveField(
            model_name='choreschedule',
            name='due_tuesday',
        ),
        migrations.RemoveField(
            model_name='choreschedule',
            name='due_wednesday',
        ),
        migrations.AddField(
            model_name='choreschedule',
            name='rotation_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ScheduleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_day_of_week', models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=255)),
                ('due_day_of_week', models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=255)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='chores.choreschedule')),
            ],
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_incomplete', models.BooleanField(default=False)),
                ('marked_incomplete_on', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='chores.chorescheduleorder')),
                ('schedule_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='chores.scheduletask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ChoreAssignment',
        ),
    ]
