# Generated by Django 5.2.5 on 2025-09-05 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0006_remove_choreschedule_due_friday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choreschedule',
            name='chore',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='chores.chore'),
        ),
    ]
