# Generated by Django 5.2.5 on 2025-09-05 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0007_alter_choreschedule_chore'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='completed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='completed_tasks', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choreschedule',
            name='chore',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='chores.chore'),
        ),
        migrations.AlterField(
            model_name='scheduletask',
            name='due_day_of_week',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=255),
        ),
        migrations.AlterField(
            model_name='scheduletask',
            name='start_day_of_week',
            field=models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=255),
        ),
    ]
