# Generated by Django 5.2.5 on 2025-09-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0008_usertask_completed_by_alter_choreschedule_chore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='overdue',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduletask',
            name='due_day_of_week',
            field=models.IntegerField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')]),
        ),
        migrations.AlterField(
            model_name='scheduletask',
            name='start_day_of_week',
            field=models.IntegerField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')]),
        ),
    ]
