# Generated by Django 5.2.5 on 2025-09-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0010_alter_scheduletask_due_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
    ]
