# Generated by Django 5.2.5 on 2025-09-05 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0011_alter_usertask_overdue'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='due_by',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 5, 21, 33, 20, 497447, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
