# Generated by Django 5.2.5 on 2025-09-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0012_usertask_due_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='completed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='due_by',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='marked_incomplete_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
