# Generated by Django 5.2.5 on 2025-09-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0013_alter_usertask_completed_on_alter_usertask_due_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletask',
            name='name',
            field=models.CharField(default='Update Me', max_length=255),
            preserve_default=False,
        ),
    ]
