# Generated by Django 5.2.5 on 2025-09-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0014_scheduletask_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='choreschedule',
            name='active_order_id',
            field=models.IntegerField(default=0),
        ),
    ]
