# Generated by Django 5.2.5 on 2025-09-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0015_choreschedule_active_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='overdue_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
