# Generated by Django 5.2.5 on 2025-08-30 03:44

import accounts.models
import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+19707999310', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
